### ISSUE TITLE
Return insert id for models with associations

### ISSUE THREAD

**Issue by tejainece** [Jaguar-dart/jaguar_orm#26]

**Comment by tejainece** [comment]
@jaumard Fixed by https://github.com/Jaguar-dart/jaguar_orm/commit/aee69f74dfa7d5fbe953cccfc0d6b940ba0bba21

Also updated the sqflite example: https://github.com/jaguar-orm/sqflite

**Comment by jaumard** [comment]
Cool ! I'll check that thanks !

**Comment by jaumard** [comment]
There still a problem @tejainece :/
Here is what you push (so I guess with your fix)

```
Future<dynamic> insert(Post model, {bool cascade: false}) async {
    final Insert insert = inserter.setMany(toSetColumns(model));
    var retId = await execInsert(insert);
    if (cascade) {
      Post newModel;
      if (model.item != null) {
        newModel ??= await find(model.id);
        itemBean.associatePost(model.item, newModel);
        await itemBean.insert(model.item);
      }
    }
    return retId;
  }
```

the problem is here `newModel ??= await find(model.id);` 
model.id is null in case of auto increment, you need to have `newModel ??= await find(retId);` instead

**Comment by tejainece** [comment]
Fixing it.

**Comment by tejainece** [comment]
Fixed by https://github.com/Jaguar-dart/jaguar_orm/commit/2bd9d814635a9cfffc90e3024afd949d0cf5c086

Also updated the sqflite example.
